### ISSUE TITLE
Fullscreen Selector Doesn't Work

### ISSUE THREAD

**Issue by DerekBuntin** [stephenscaff/vimeo-playlists#29]
The fullscreen selector doesn't work because the element is hardcoded to select the first iframe:

vimeo-playlist.js line 379, this would be fine if there are no other iframes on the page or the video is the first but given many use Google Tag Manager which uses an iframe element right after the body tag this is what's selected.

`let vid = document.querySelector('iframe')`

**Comment by stephenscaff** [comment]
I'll take a look. Thanks.

**Comment by stephenscaff** [comment]
Okay, should be good to go now. See #34.

`toggleFullscreen()` has been updated to target the Vimeo iframe instance via `this.player.element`.

Also made the fullscreen keycode default to null, so you can defined with desired key (ie: `KeyF`), which seems to make better sense.

This was a great callout.

Thanks!
